//
// Created by Varun Srinivasan on 24/11/2024.
//

#ifndef CMAKESFMLPROJECT_POWERUPTYPES_H
#define CMAKESFMLPROJECT_POWERUPTYPES_H

enum class PowerUpType {
    SCATTER_BULLET,
    RPG
};

#endif //CMAKESFMLPROJECT_POWERUPTYPES_H
